### ISSUE TITLE
Runtime usage?

### ISSUE THREAD

**Issue by denizzzka** [jjpatel/dhtags#2]
Found what Usage example line evaluates at compile time:
```D
auto someHtml = div(span(className="text")("Some text"));
```

Can you exmplain runtime usage? Especially type and concatenation.

**Comment by jjpatel** [comment]
At this point, there's not much you can do with resulting type before converting it to a string. You can of nest it in other tags if you wanted to wrap it in another div for example.

Unfortunately, I don't have the time anymore to make improvements so you can consider it abandoned. Feel free to fork it though and make your own changes!

**Comment by denizzzka** [comment]
How to nest string (or HtmlString?) to tag without escaping?

> Unfortunately, I don't have the time anymore to make improvements so you can consider it abandoned. Feel free to fork it though and make your own changes!

Okay

**Comment by jjpatel** [comment]
> How to nest string (or HtmlString?) to tag without escaping?

`toString` and `toPrettyString` takes an optional argument to toggle escaping.

```d
auto hello = div(className="my-div")("<h1>Hello!</h1>");
writeln(hello.toPrettyString(false));
```

```html
<div class="my-div"><h1>Hello!</h1></div>
```

**Comment by denizzzka** [comment]
Thanks!
